Repository cjmellor/level-up, pull requests merged in 2023-08, with the labels that each got.

#22 fix: Return correct value on next level check
  src/Concerns/GiveExperience.php
  tests/Concerns/GiveExperienceTest.php
  tests/Listeners/PointsIncreasedListenerTest.php
Labels: bug

#28 fix: set timestamps when creating achievements
  src/Concerns/HasAchievements.php
Labels: bug

#29 Streaks
  README.md
  UPGRADE.md
  composer.json
  config/level-up.php
  database/factories/ActivityFactory.php
  database/factories/StreakFactory.php
  database/migrations/create_streak_activities_table.php.stub
  database/migrations/create_streak_histories_table.php.stub
  database/migrations/create_streaks_table.php.stub
  src/Concerns/HasStreaks.php
  src/Events/StreakBroken.php
  src/Events/StreakIncreased.php
  src/Events/StreakStarted.php
  src/LevelUpServiceProvider.php
  src/Models/Activity.php
  src/Models/Pivots/AchievementUser.php
  src/Models/Streak.php
  src/Models/StreakHistory.php
  src/Providers/MultiplierServiceProvider.php
  src/Services/LeaderboardService.php
  src/Services/MultiplierService.php
  tests/Concerns/HasStreaksTest.php
  tests/Fixtures/User.php
  tests/TestCase.php
Labels: documentation, enhancement

#26 Possible `nextLevelAt()` Bug
  src/Concerns/GiveExperience.php
Labels: bug

#27 Missing Test
  tests/Listeners/PointsIncreasedListenerTest.php
Labels: bug, enhancement

#32 Adds a feature to freeze a streak
  .github/workflows/run-linter.yml
  README.md
  config/level-up.php
  database/migrations/add_streak_freeze_feature_columns_to_streaks_table.php.stub
  src/Concerns/HasStreaks.php
  src/Events/StreakFrozen.php
  src/Events/StreakUnfroze.php
  src/LevelUpServiceProvider.php
  src/Models/Streak.php
  tests/Concerns/HasStreaksTest.php
  tests/TestCase.php
Labels: enhancement

#33 Refactor Tests
  composer.json
  tests/Concerns/HasStreaksTest.php
Labels: enhancement

#37 Add custom expectation for Carbon instances and level cap validation
  src/Concerns/GiveExperience.php
  tests/Concerns/GiveExperienceTest.php
  tests/Concerns/HasStreaksTest.php
  tests/Pest.php
Labels: enhancement
